#!/bin/sh

argv=$@

sudoCmd(){
    cmd=$@
    expect -c "
        set timeout 3
        spawn sudo $cmd
        expect \"*assword\" {
            send \"$PASSWD\r\"
            interact
            exit
        }
    expect eof"
}

sudoCmd $argv
